spring:
 profiles:
  default: default
 config:
  import: "optional:configserver:http://localhost:8888"
 application:
  name: ms-order
 jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
 datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/orders-db
