spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: brayan
    password: brayan
    url: jdbc:mysql://localhost:3307/products-db-prod
    driver-class-name: com.mysql.cj.jdbc.Driver
